import PokeData from "../../../src/models/PokeData";

const mocksPokemon: PokeData[] = [
  {
    id: 1,
    number: 1,
    name: "bulbasaur",
    description: "A strange seed was planted on its back at birth.",
    height: "0.7",
    weight: "6.9",
    types: ["grass", "poison"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
  },
  {
    id: 4,
    number: 4,
    name: "charmander",
    description: "Obviously prefers hot places.",
    height: "0.6",
    weight: "8.5",
    types: ["fire"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
  },
  {
    id: 7,
    number: 7,
    name: "squirtle",
    description: "Shoots water at prey while in the water.",
    height: "0.5",
    weight: "9.0",
    types: ["water"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
  },
  {
    id: 25,
    number: 25,
    name: "pikachu",
    description: "When several of these Pokémon gather, their electricity could build and cause lightning storms.",
    height: "0.4",
    weight: "6.0",
    types: ["electric"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png",
  },
  {
    id: 144,
    number: 144,
    name: "articuno",
    description: "A legendary bird Pokémon. It freezes water that is contained in winter air and makes it snow.",
    height: "1.7",
    weight: "55.4",
    types: ["ice", "flying"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png",
  },
  {
    id: 66,
    number: 66,
    name: "machop",
    description: "Loves to build its muscles. It trains in all styles of martial arts.",
    height: "0.8",
    weight: "19.5",
    types: ["fighting"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png",
  },
  {
    id: 27,
    number: 27,
    name: "sandshrew",
    description: "Burrows deep underground in arid locations far from water.",
    height: "0.6",
    weight: "12.0",
    types: ["ground"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png",
  },
  {
    id: 41,
    number: 41,
    name: "zubat",
    description: "Forms colonies in perpetually dark places.",
    height: "0.8",
    weight: "7.5",
    types: ["poison", "flying"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png",
  },
  {
    id: 63,
    number: 63,
    name: "abra",
    description: "Using its ability to read minds, it will identify impending danger and teleport to safety.",
    height: "0.9",
    weight: "19.5",
    types: ["psychic"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png",
  },
  {
    id: 10,
    number: 10,
    name: "caterpie",
    description: "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.",
    height: "0.3",
    weight: "2.9",
    types: ["bug"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
  },
  {
    id: 74,
    number: 74,
    name: "geodude",
    description: "Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.",
    height: "0.4",
    weight: "20.0",
    types: ["rock", "ground"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png",
  },
  {
    id: 92,
    number: 92,
    name: "gastly",
    description: "Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice.",
    height: "1.3",
    weight: "0.1",
    types: ["ghost", "poison"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png",
  },
  {
    id: 147,
    number: 147,
    name: "dratini",
    description: "Long considered a mythical Pokémon until recently when a small colony was found living underwater.",
    height: "1.8",
    weight: "3.3",
    types: ["dragon"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png",
  },
  {
    id: 197,
    number: 197,
    name: "umbreon",
    description: "When agitated, this Pokémon protects itself by spraying poisonous sweat from its pores.",
    height: "1.0",
    weight: "27.0",
    types: ["dark"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/197.png",
  },
  {
    id: 304,
    number: 304,
    name: "aron",
    description: "It eats iron ore - and sometimes railroad tracks - to build up its steel body.",
    height: "0.4",
    weight: "60.0",
    types: ["steel", "rock"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/304.png",
  },
  {
    id: 35,
    number: 35,
    name: "clefairy",
    description: "Its magical and cute appeal has many admirers. It is rare and found only in certain areas.",
    height: "0.6",
    weight: "7.5",
    types: ["fairy"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png",
  },
  {
    id: 19,
    number: 19,
    name: "rattata",
    description: "Bites anything when it attacks. Small and very quick, it is a common sight in many places.",
    height: "0.3",
    weight: "3.5",
    types: ["normal"],
    image: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",
  },
];

export default mocksPokemon;
